from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import *
import interface.res.res_rc


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 500)
        MainWindow.setMinimumSize(QtCore.QSize(900, 500))
        MainWindow.setMaximumSize(QtCore.QSize(900, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("#frame_links QPushButton {\n"
"    background-color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.511, y2:1, stop:0 rgba(212, 0, 255, 255), stop:1 rgba(155, 0, 194, 255));\n"
"    color: #202020;\n"
"    border-radius: 50px;\n"
"}\n"
"#frame_links QPushButton:hover {\n"
"    background-color:#202020;\n"
"    color: qlineargradient(spread:pad, x1:0.489, y1:0, x2:0.511, y2:1, stop:0 rgba(212, 0, 255, 255), stop:1 rgba(155, 0, 194, 255));\n"
"}\n"
"#frame_links QPushButton:pressed {\n"
"    background-color: #202020;\n"
"    color: #505050;\n"
"}\n"
"\n"
"QLineEdit {\n"
"    border-radius: 3px;\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    border: 1px solid #C9C9C9;\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 1px solid #0078D4;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background-color: #E0E0E0;\n"
"    border: 1px solid #BABABA;\n"
"}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 10, 902, 475))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_acc = QtWidgets.QWidget()
        self.tab_acc.setObjectName("tab_acc")
        self.frame_2 = QtWidgets.QFrame(self.tab_acc)
        self.frame_2.setGeometry(QtCore.QRect(0, 0, 900, 40))
        self.frame_2.setMinimumSize(QtCore.QSize(900, 40))
        self.frame_2.setMaximumSize(QtCore.QSize(900, 40))
        self.frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setLineWidth(0)
        self.frame_2.setObjectName("frame_2")
        self.frame = QtWidgets.QFrame(self.frame_2)
        self.frame.setGeometry(QtCore.QRect(5, 5, 410, 30))
        self.frame.setMinimumSize(QtCore.QSize(410, 30))
        self.frame.setMaximumSize(QtCore.QSize(410, 30))
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setLineWidth(0)
        self.frame.setObjectName("frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login_input = QtWidgets.QLineEdit(self.frame)
        self.login_input.setMinimumSize(QtCore.QSize(140, 24))
        self.login_input.setMaximumSize(QtCore.QSize(140, 24))
        self.login_input.setObjectName("login_input")
        self.horizontalLayout.addWidget(self.login_input)
        self.password_input = QtWidgets.QLineEdit(self.frame)
        self.password_input.setMinimumSize(QtCore.QSize(140, 24))
        self.password_input.setMaximumSize(QtCore.QSize(140, 24))
        self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_input.setObjectName("password_input")
        self.horizontalLayout.addWidget(self.password_input)
        self.add_account_btn = QtWidgets.QPushButton(self.frame)
        self.add_account_btn.setMinimumSize(QtCore.QSize(110, 26))
        self.add_account_btn.setMaximumSize(QtCore.QSize(110, 26))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/add_acc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_account_btn.setIcon(icon1)
        self.add_account_btn.setObjectName("add_account_btn")
        self.horizontalLayout.addWidget(self.add_account_btn)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(480, 5, 410, 30))
        self.frame_3.setMinimumSize(QtCore.QSize(410, 30))
        self.frame_3.setMaximumSize(QtCore.QSize(410, 30))
        self.frame_3.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setLineWidth(0)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.select_server = QtWidgets.QComboBox(self.frame_3)
        self.select_server.setMinimumSize(QtCore.QSize(60, 26))
        self.select_server.setMaximumSize(QtCore.QSize(60, 26))
        self.select_server.setMaxVisibleItems(14)
        self.select_server.setObjectName("select_server")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.select_server.addItem("")
        self.horizontalLayout_2.addWidget(self.select_server)
        self.login_btn = QtWidgets.QPushButton(self.frame_3)
        self.login_btn.setMinimumSize(QtCore.QSize(170, 26))
        self.login_btn.setMaximumSize(QtCore.QSize(170, 26))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/login_acc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.login_btn.setIcon(icon2)
        self.login_btn.setObjectName("login_btn")
        self.horizontalLayout_2.addWidget(self.login_btn)
        self.manage_btn = QtWidgets.QPushButton(self.frame_3)
        self.manage_btn.setMinimumSize(QtCore.QSize(170, 26))
        self.manage_btn.setMaximumSize(QtCore.QSize(170, 26))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/manage_acc.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.manage_btn.setIcon(icon3)
        self.manage_btn.setObjectName("manage_btn")
        self.horizontalLayout_2.addWidget(self.manage_btn)
        self.acc_list = QtWidgets.QTableWidget(self.tab_acc)
        self.acc_list.setGeometry(QtCore.QRect(7, 40, 882, 402))
        self.acc_list.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.acc_list.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.acc_list.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.acc_list.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.acc_list.setVerticalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.acc_list.setHorizontalScrollMode(QtWidgets.QAbstractItemView.ScrollPerPixel)
        self.acc_list.setObjectName("acc_list")
        self.acc_list.setColumnCount(0)
        self.acc_list.setRowCount(0)
        self.acc_list.horizontalHeader().setDefaultSectionSize(142)
        self.acc_list.horizontalHeader().setHighlightSections(False)
        self.acc_list.horizontalHeader().setMinimumSectionSize(1)
        self.acc_list.verticalHeader().setVisible(False)
        self.acc_list.verticalHeader().setHighlightSections(False)
        self.tabWidget.addTab(self.tab_acc, "")
        self.tab_manage_acc = QtWidgets.QWidget()
        self.tab_manage_acc.setObjectName("tab_manage_acc")
        self.frame_14 = QtWidgets.QFrame(self.tab_manage_acc)
        self.frame_14.setGeometry(QtCore.QRect(0, 0, 900, 450))
        self.frame_14.setMinimumSize(QtCore.QSize(900, 450))
        self.frame_14.setMaximumSize(QtCore.QSize(900, 450))
        self.frame_14.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setLineWidth(0)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_2.setContentsMargins(10, 10, 15, 10)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_14)
        self.frame_4.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setLineWidth(0)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setMinimumSize(QtCore.QSize(367, 30))
        self.frame_5.setMaximumSize(QtCore.QSize(367, 30))
        self.frame_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setLineWidth(0)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.frame_5)
        self.label.setMinimumSize(QtCore.QSize(100, 0))
        self.label.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.m_login_input = QtWidgets.QLineEdit(self.frame_5)
        self.m_login_input.setMinimumSize(QtCore.QSize(200, 24))
        self.m_login_input.setObjectName("m_login_input")
        self.horizontalLayout_3.addWidget(self.m_login_input)
        self.copy_username = QtWidgets.QPushButton(self.frame_5)
        self.copy_username.setMinimumSize(QtCore.QSize(26, 26))
        self.copy_username.setMaximumSize(QtCore.QSize(26, 26))
        self.copy_username.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/copy.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.copy_username.setIcon(icon4)
        self.copy_username.setObjectName("copy_username")
        self.horizontalLayout_3.addWidget(self.copy_username)
        self.verticalLayout.addWidget(self.frame_5)
        self.frame_10 = QtWidgets.QFrame(self.frame_4)
        self.frame_10.setMinimumSize(QtCore.QSize(367, 30))
        self.frame_10.setMaximumSize(QtCore.QSize(367, 30))
        self.frame_10.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setLineWidth(0)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(5)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_2 = QtWidgets.QLabel(self.frame_10)
        self.label_2.setMinimumSize(QtCore.QSize(100, 0))
        self.label_2.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_8.addWidget(self.label_2)
        self.m_password_input = QtWidgets.QLineEdit(self.frame_10)
        self.m_password_input.setMinimumSize(QtCore.QSize(200, 24))
        self.m_password_input.setObjectName("m_password_input")
        self.horizontalLayout_8.addWidget(self.m_password_input)
        self.copy_password = QtWidgets.QPushButton(self.frame_10)
        self.copy_password.setMinimumSize(QtCore.QSize(26, 26))
        self.copy_password.setMaximumSize(QtCore.QSize(26, 26))
        self.copy_password.setText("")
        self.copy_password.setIcon(icon4)
        self.copy_password.setObjectName("copy_password")
        self.horizontalLayout_8.addWidget(self.copy_password)
        self.verticalLayout.addWidget(self.frame_10)
        self.frame_11 = QtWidgets.QFrame(self.frame_4)
        self.frame_11.setMinimumSize(QtCore.QSize(367, 30))
        self.frame_11.setMaximumSize(QtCore.QSize(367, 30))
        self.frame_11.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setLineWidth(0)
        self.frame_11.setObjectName("frame_11")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.frame_11)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_3 = QtWidgets.QLabel(self.frame_11)
        self.label_3.setMinimumSize(QtCore.QSize(100, 0))
        self.label_3.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_9.addWidget(self.label_3)
        self.m_summoner_input = QtWidgets.QLineEdit(self.frame_11)
        self.m_summoner_input.setEnabled(False)
        self.m_summoner_input.setMinimumSize(QtCore.QSize(200, 24))
        self.m_summoner_input.setObjectName("m_summoner_input")
        self.horizontalLayout_9.addWidget(self.m_summoner_input)
        self.copy_summoner = QtWidgets.QPushButton(self.frame_11)
        self.copy_summoner.setMinimumSize(QtCore.QSize(26, 26))
        self.copy_summoner.setMaximumSize(QtCore.QSize(26, 26))
        self.copy_summoner.setText("")
        self.copy_summoner.setIcon(icon4)
        self.copy_summoner.setObjectName("copy_summoner")
        self.horizontalLayout_9.addWidget(self.copy_summoner)
        self.verticalLayout.addWidget(self.frame_11)
        self.frame_12 = QtWidgets.QFrame(self.frame_4)
        self.frame_12.setMinimumSize(QtCore.QSize(336, 30))
        self.frame_12.setMaximumSize(QtCore.QSize(336, 30))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setLineWidth(0)
        self.frame_12.setObjectName("frame_12")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.frame_12)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setSpacing(5)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(self.frame_12)
        self.label_4.setMinimumSize(QtCore.QSize(100, 0))
        self.label_4.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.m_soloq_input = QtWidgets.QLineEdit(self.frame_12)
        self.m_soloq_input.setEnabled(False)
        self.m_soloq_input.setMinimumSize(QtCore.QSize(200, 24))
        self.m_soloq_input.setObjectName("m_soloq_input")
        self.horizontalLayout_10.addWidget(self.m_soloq_input)
        self.verticalLayout.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_4)
        self.frame_13.setMinimumSize(QtCore.QSize(336, 30))
        self.frame_13.setMaximumSize(QtCore.QSize(336, 30))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setLineWidth(0)
        self.frame_13.setObjectName("frame_13")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.frame_13)
        self.horizontalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_11.setSpacing(5)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_5 = QtWidgets.QLabel(self.frame_13)
        self.label_5.setMinimumSize(QtCore.QSize(100, 0))
        self.label_5.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_11.addWidget(self.label_5)
        self.m_flexq_input = QtWidgets.QLineEdit(self.frame_13)
        self.m_flexq_input.setEnabled(False)
        self.m_flexq_input.setMinimumSize(QtCore.QSize(200, 24))
        self.m_flexq_input.setObjectName("m_flexq_input")
        self.horizontalLayout_11.addWidget(self.m_flexq_input)
        self.verticalLayout.addWidget(self.frame_13)
        self.frame_8 = QtWidgets.QFrame(self.frame_4)
        self.frame_8.setMinimumSize(QtCore.QSize(336, 30))
        self.frame_8.setMaximumSize(QtCore.QSize(336, 30))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setLineWidth(0)
        self.frame_8.setObjectName("frame_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_8)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(22)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.frame_6 = QtWidgets.QFrame(self.frame_8)
        self.frame_6.setMinimumSize(QtCore.QSize(112, 30))
        self.frame_6.setMaximumSize(QtCore.QSize(112, 30))
        self.frame_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setLineWidth(0)
        self.frame_6.setObjectName("frame_6")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_6)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_6 = QtWidgets.QLabel(self.frame_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_4.addWidget(self.label_6)
        self.m_server_input = QtWidgets.QLineEdit(self.frame_6)
        self.m_server_input.setEnabled(False)
        self.m_server_input.setMinimumSize(QtCore.QSize(60, 24))
        self.m_server_input.setMaximumSize(QtCore.QSize(16777215, 24))
        self.m_server_input.setObjectName("m_server_input")
        self.horizontalLayout_4.addWidget(self.m_server_input)
        self.horizontalLayout_7.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_8)
        self.frame_7.setMinimumSize(QtCore.QSize(90, 30))
        self.frame_7.setMaximumSize(QtCore.QSize(90, 30))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setLineWidth(0)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(5)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_7 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setLineWidth(0)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_5.addWidget(self.label_7)
        self.m_be_input = QtWidgets.QLineEdit(self.frame_7)
        self.m_be_input.setEnabled(False)
        self.m_be_input.setMinimumSize(QtCore.QSize(0, 24))
        self.m_be_input.setMaximumSize(QtCore.QSize(16777215, 24))
        self.m_be_input.setObjectName("m_be_input")
        self.horizontalLayout_5.addWidget(self.m_be_input)
        self.horizontalLayout_7.addWidget(self.frame_7)
        self.frame_9 = QtWidgets.QFrame(self.frame_8)
        self.frame_9.setMinimumSize(QtCore.QSize(90, 30))
        self.frame_9.setMaximumSize(QtCore.QSize(90, 30))
        self.frame_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setLineWidth(0)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(5)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_8 = QtWidgets.QLabel(self.frame_9)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setLineWidth(0)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_6.addWidget(self.label_8)
        self.m_rp_input = QtWidgets.QLineEdit(self.frame_9)
        self.m_rp_input.setEnabled(False)
        self.m_rp_input.setMinimumSize(QtCore.QSize(0, 24))
        self.m_rp_input.setMaximumSize(QtCore.QSize(16777215, 24))
        self.m_rp_input.setObjectName("m_rp_input")
        self.horizontalLayout_6.addWidget(self.m_rp_input)
        self.horizontalLayout_7.addWidget(self.frame_9)
        self.verticalLayout.addWidget(self.frame_8)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 50))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setLineWidth(0)
        self.frame_15.setObjectName("frame_15")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.frame_15)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.frame_16 = QtWidgets.QFrame(self.frame_15)
        self.frame_16.setMinimumSize(QtCore.QSize(336, 50))
        self.frame_16.setMaximumSize(QtCore.QSize(336, 50))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setLineWidth(0)
        self.frame_16.setObjectName("frame_16")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.frame_16)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(10)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.get_data_btn = QtWidgets.QPushButton(self.frame_16)
        self.get_data_btn.setMinimumSize(QtCore.QSize(196, 40))
        self.get_data_btn.setMaximumSize(QtCore.QSize(196, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.get_data_btn.setFont(font)
        self.get_data_btn.setObjectName("get_data_btn")
        self.horizontalLayout_13.addWidget(self.get_data_btn)
        self.save_changes_btn = QtWidgets.QPushButton(self.frame_16)
        self.save_changes_btn.setMinimumSize(QtCore.QSize(130, 40))
        self.save_changes_btn.setMaximumSize(QtCore.QSize(130, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.save_changes_btn.setFont(font)
        self.save_changes_btn.setObjectName("save_changes_btn")
        self.horizontalLayout_13.addWidget(self.save_changes_btn)
        self.horizontalLayout_12.addWidget(self.frame_16)
        self.dele_account_btn = QtWidgets.QPushButton(self.frame_15)
        self.dele_account_btn.setMinimumSize(QtCore.QSize(150, 40))
        self.dele_account_btn.setMaximumSize(QtCore.QSize(120, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dele_account_btn.setFont(font)
        self.dele_account_btn.setObjectName("dele_account_btn")
        self.horizontalLayout_12.addWidget(self.dele_account_btn, 0, QtCore.Qt.AlignRight)
        self.verticalLayout_2.addWidget(self.frame_15, 0, QtCore.Qt.AlignBottom)
        self.tabWidget.addTab(self.tab_manage_acc, "")
        self.tab_credits = QtWidgets.QWidget()
        self.tab_credits.setObjectName("tab_credits")
        self.frame_17 = QtWidgets.QFrame(self.tab_credits)
        self.frame_17.setGeometry(QtCore.QRect(0, 0, 900, 450))
        self.frame_17.setMinimumSize(QtCore.QSize(900, 450))
        self.frame_17.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setLineWidth(0)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setLineWidth(0)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.frame_18)
        self.label_9.setLineWidth(0)
        self.label_9.setTextFormat(QtCore.Qt.RichText)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.frame_links = QtWidgets.QFrame(self.frame_18)
        self.frame_links.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_links.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_links.setLineWidth(0)
        self.frame_links.setObjectName("frame_links")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.frame_links)
        self.horizontalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_14.setSpacing(0)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.disc_btn = QtWidgets.QPushButton(self.frame_links)
        self.disc_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.disc_btn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(70)
        self.disc_btn.setFont(font)
        self.disc_btn.setObjectName("disc_btn")
        self.horizontalLayout_14.addWidget(self.disc_btn)
        self.tt_btn = QtWidgets.QPushButton(self.frame_links)
        self.tt_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.tt_btn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(70)
        self.tt_btn.setFont(font)
        self.tt_btn.setObjectName("tt_btn")
        self.horizontalLayout_14.addWidget(self.tt_btn)
        self.insta_btn = QtWidgets.QPushButton(self.frame_links)
        self.insta_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.insta_btn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(70)
        self.insta_btn.setFont(font)
        self.insta_btn.setObjectName("insta_btn")
        self.horizontalLayout_14.addWidget(self.insta_btn)
        self.git_btn = QtWidgets.QPushButton(self.frame_links)
        self.git_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.git_btn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(70)
        self.git_btn.setFont(font)
        self.git_btn.setObjectName("git_btn")
        self.horizontalLayout_14.addWidget(self.git_btn)
        self.pp_btn = QtWidgets.QPushButton(self.frame_links)
        self.pp_btn.setMinimumSize(QtCore.QSize(100, 100))
        self.pp_btn.setMaximumSize(QtCore.QSize(100, 100))
        font = QtGui.QFont()
        font.setFamily("Social Media Circled")
        font.setPointSize(70)
        self.pp_btn.setFont(font)
        self.pp_btn.setObjectName("pp_btn")
        self.horizontalLayout_14.addWidget(self.pp_btn)
        self.verticalLayout_3.addWidget(self.frame_links)
        self.verticalLayout_4.addWidget(self.frame_18)
        self.tabWidget.addTab(self.tab_credits, "")
        self.select_elo = QtWidgets.QComboBox(self.centralwidget)
        self.select_elo.setGeometry(QtCore.QRect(730, 2, 160, 26))
        self.select_elo.setMaxVisibleItems(11)
        self.select_elo.setObjectName("select_elo")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        self.select_elo.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.select_server.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "League Account Manager"))
        self.login_input.setPlaceholderText(_translate("MainWindow", "Login"))
        self.password_input.setPlaceholderText(_translate("MainWindow", "Password"))
        self.add_account_btn.setText(_translate("MainWindow", " Add Account"))
        self.select_server.setItemText(0, _translate("MainWindow", "ALL"))
        self.select_server.setItemText(1, _translate("MainWindow", "BR"))
        self.select_server.setItemText(2, _translate("MainWindow", "EUNE"))
        self.select_server.setItemText(3, _translate("MainWindow", "EUW"))
        self.select_server.setItemText(4, _translate("MainWindow", "JP"))
        self.select_server.setItemText(5, _translate("MainWindow", "KR"))
        self.select_server.setItemText(6, _translate("MainWindow", "LAN"))
        self.select_server.setItemText(7, _translate("MainWindow", "LAS"))
        self.select_server.setItemText(8, _translate("MainWindow", "NA"))
        self.select_server.setItemText(9, _translate("MainWindow", "OC"))
        self.select_server.setItemText(10, _translate("MainWindow", "RU"))
        self.select_server.setItemText(11, _translate("MainWindow", "TR"))
        self.select_server.setItemText(12, _translate("MainWindow", "PBE"))
        self.select_server.setItemText(13, _translate("MainWindow", "???"))
        self.login_btn.setText(_translate("MainWindow", " Login to selected account"))
        self.manage_btn.setText(_translate("MainWindow", " Manage Selected Account"))
        self.acc_list.setSortingEnabled(True)
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_acc), _translate("MainWindow", "Accounts"))
        self.label.setText(_translate("MainWindow", "Login"))
        self.copy_username.setToolTip(_translate("MainWindow", "Copy to clipboard"))
        self.label_2.setText(_translate("MainWindow", "Password"))
        self.copy_password.setToolTip(_translate("MainWindow", "Copy to clipboard"))
        self.label_3.setText(_translate("MainWindow", "Summoner"))
        self.copy_summoner.setToolTip(_translate("MainWindow", "Copy to clipboard"))
        self.label_4.setText(_translate("MainWindow", "SoloQ"))
        self.label_5.setText(_translate("MainWindow", "FlexQ"))
        self.label_6.setText(_translate("MainWindow", "Server"))
        self.label_7.setText(_translate("MainWindow", "BE"))
        self.label_8.setText(_translate("MainWindow", "RP"))
        self.get_data_btn.setText(_translate("MainWindow", "Get Ranked/Store Data"))
        self.save_changes_btn.setText(_translate("MainWindow", "Save Changes"))
        self.dele_account_btn.setText(_translate("MainWindow", "Delete Account"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_manage_acc), _translate("MainWindow", "Manage Account"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">League Account Manager</span></p><p align=\"center\"><span style=\" font-size:20pt;\">Developed by: Gabriel Viana</span></p></body></html>"))
        self.disc_btn.setToolTip(_translate("MainWindow", "Copy my Discord username to clipboard"))
        self.disc_btn.setStatusTip(_translate("MainWindow", "Copy my discord username to clipboard... (Useful if you want to contact me through discord)"))
        self.disc_btn.setText(_translate("MainWindow", "Y"))
        self.tt_btn.setToolTip(_translate("MainWindow", "Open my Twitter profile in browser"))
        self.tt_btn.setStatusTip(_translate("MainWindow", "Open my Twitter profile in browser..."))
        self.tt_btn.setText(_translate("MainWindow", "D"))
        self.insta_btn.setToolTip(_translate("MainWindow", "Open my Instagram profile in browser"))
        self.insta_btn.setStatusTip(_translate("MainWindow", "Open my Instagram profile in browser..."))
        self.insta_btn.setText(_translate("MainWindow", "Z"))
        self.git_btn.setToolTip(_translate("MainWindow", "Open my GitHub profile in browser"))
        self.git_btn.setStatusTip(_translate("MainWindow", "Open my GitHub profile in browser..."))
        self.git_btn.setText(_translate("MainWindow", ")"))
        self.pp_btn.setToolTip(_translate("MainWindow", "Buy me a coffee"))
        self.pp_btn.setStatusTip(_translate("MainWindow", "If this software is useful to you and you want to help me in some way, buy me a coffee... ^^"))
        self.pp_btn.setText(_translate("MainWindow", "Z"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_credits), _translate("MainWindow", "Credits"))
        self.select_elo.setItemText(0, _translate("MainWindow", "All"))
        self.select_elo.setItemText(1, _translate("MainWindow", "Unranked"))
        self.select_elo.setItemText(2, _translate("MainWindow", "Iron"))
        self.select_elo.setItemText(3, _translate("MainWindow", "Bronze"))
        self.select_elo.setItemText(4, _translate("MainWindow", "Silver"))
        self.select_elo.setItemText(5, _translate("MainWindow", "Gold"))
        self.select_elo.setItemText(6, _translate("MainWindow", "Platinum"))
        self.select_elo.setItemText(7, _translate("MainWindow", "Diamond"))
        self.select_elo.setItemText(8, _translate("MainWindow", "Master"))
        self.select_elo.setItemText(9, _translate("MainWindow", "Grand Master"))
        self.select_elo.setItemText(10, _translate("MainWindow", "Challenger"))
